### ISSUE TITLE
Can not instal mammoth-viewer

### ISSUE THREAD

**Issue by joost68** [mwilliamson/python-mammoth-viewer#1]
After
`pip install mammoth-viewer`
I get:
```
ERROR: Could not find a version that satisfies the requirement mammoth-viewer
ERROR: No matching distribution found for mammoth-viewer
```
I'm on Windows 10
python version is 3.9.1
pip version is 21.0

**Comment by mwilliamson** [comment]
I'd forgotten that this project even exists! I don't think I ever got around to publishing this to PyPI, so the pip install command won't work (now removed from the README).
